/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AAccessProgramVarDeclarations extends PProgramVarDeclarations
{
    private PProgramAccessDecls _programAccessDecls_;

    public AAccessProgramVarDeclarations()
    {
        // Constructor
    }

    public AAccessProgramVarDeclarations(
        @SuppressWarnings("hiding") PProgramAccessDecls _programAccessDecls_)
    {
        // Constructor
        setProgramAccessDecls(_programAccessDecls_);

    }

    @Override
    public Object clone()
    {
        return new AAccessProgramVarDeclarations(
            cloneNode(this._programAccessDecls_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAccessProgramVarDeclarations(this);
    }

    public PProgramAccessDecls getProgramAccessDecls()
    {
        return this._programAccessDecls_;
    }

    public void setProgramAccessDecls(PProgramAccessDecls node)
    {
        if(this._programAccessDecls_ != null)
        {
            this._programAccessDecls_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programAccessDecls_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programAccessDecls_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programAccessDecls_ == child)
        {
            this._programAccessDecls_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programAccessDecls_ == oldChild)
        {
            setProgramAccessDecls((PProgramAccessDecls) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
