/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AArraySpecInitialization extends PArraySpecInitialization
{
    private TColonEq _colonEq_;
    private PArrayInitialization _arrayInitialization_;

    public AArraySpecInitialization()
    {
        // Constructor
    }

    public AArraySpecInitialization(
        @SuppressWarnings("hiding") TColonEq _colonEq_,
        @SuppressWarnings("hiding") PArrayInitialization _arrayInitialization_)
    {
        // Constructor
        setColonEq(_colonEq_);

        setArrayInitialization(_arrayInitialization_);

    }

    @Override
    public Object clone()
    {
        return new AArraySpecInitialization(
            cloneNode(this._colonEq_),
            cloneNode(this._arrayInitialization_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArraySpecInitialization(this);
    }

    public TColonEq getColonEq()
    {
        return this._colonEq_;
    }

    public void setColonEq(TColonEq node)
    {
        if(this._colonEq_ != null)
        {
            this._colonEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colonEq_ = node;
    }

    public PArrayInitialization getArrayInitialization()
    {
        return this._arrayInitialization_;
    }

    public void setArrayInitialization(PArrayInitialization node)
    {
        if(this._arrayInitialization_ != null)
        {
            this._arrayInitialization_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayInitialization_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colonEq_)
            + toString(this._arrayInitialization_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colonEq_ == child)
        {
            this._colonEq_ = null;
            return;
        }

        if(this._arrayInitialization_ == child)
        {
            this._arrayInitialization_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colonEq_ == oldChild)
        {
            setColonEq((TColonEq) newChild);
            return;
        }

        if(this._arrayInitialization_ == oldChild)
        {
            setArrayInitialization((PArrayInitialization) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
