/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AAssign2Statement extends PStatement
{
    private PVariableComplex _variableComplex_;
    private TColonEq _colonEq_;
    private PExpression _expression_;

    public AAssign2Statement()
    {
        // Constructor
    }

    public AAssign2Statement(
        @SuppressWarnings("hiding") PVariableComplex _variableComplex_,
        @SuppressWarnings("hiding") TColonEq _colonEq_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setVariableComplex(_variableComplex_);

        setColonEq(_colonEq_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AAssign2Statement(
            cloneNode(this._variableComplex_),
            cloneNode(this._colonEq_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssign2Statement(this);
    }

    public PVariableComplex getVariableComplex()
    {
        return this._variableComplex_;
    }

    public void setVariableComplex(PVariableComplex node)
    {
        if(this._variableComplex_ != null)
        {
            this._variableComplex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableComplex_ = node;
    }

    public TColonEq getColonEq()
    {
        return this._colonEq_;
    }

    public void setColonEq(TColonEq node)
    {
        if(this._colonEq_ != null)
        {
            this._colonEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colonEq_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variableComplex_)
            + toString(this._colonEq_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variableComplex_ == child)
        {
            this._variableComplex_ = null;
            return;
        }

        if(this._colonEq_ == child)
        {
            this._colonEq_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variableComplex_ == oldChild)
        {
            setVariableComplex((PVariableComplex) newChild);
            return;
        }

        if(this._colonEq_ == oldChild)
        {
            setColonEq((TColonEq) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
