/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ABitStringLiteralTypeNameHashed extends PBitStringLiteralTypeNameHashed
{
    private TBitStringLiteralTypeName _bitStringLiteralTypeName_;
    private THash _hash_;

    public ABitStringLiteralTypeNameHashed()
    {
        // Constructor
    }

    public ABitStringLiteralTypeNameHashed(
        @SuppressWarnings("hiding") TBitStringLiteralTypeName _bitStringLiteralTypeName_,
        @SuppressWarnings("hiding") THash _hash_)
    {
        // Constructor
        setBitStringLiteralTypeName(_bitStringLiteralTypeName_);

        setHash(_hash_);

    }

    @Override
    public Object clone()
    {
        return new ABitStringLiteralTypeNameHashed(
            cloneNode(this._bitStringLiteralTypeName_),
            cloneNode(this._hash_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABitStringLiteralTypeNameHashed(this);
    }

    public TBitStringLiteralTypeName getBitStringLiteralTypeName()
    {
        return this._bitStringLiteralTypeName_;
    }

    public void setBitStringLiteralTypeName(TBitStringLiteralTypeName node)
    {
        if(this._bitStringLiteralTypeName_ != null)
        {
            this._bitStringLiteralTypeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bitStringLiteralTypeName_ = node;
    }

    public THash getHash()
    {
        return this._hash_;
    }

    public void setHash(THash node)
    {
        if(this._hash_ != null)
        {
            this._hash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._hash_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bitStringLiteralTypeName_)
            + toString(this._hash_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bitStringLiteralTypeName_ == child)
        {
            this._bitStringLiteralTypeName_ = null;
            return;
        }

        if(this._hash_ == child)
        {
            this._hash_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bitStringLiteralTypeName_ == oldChild)
        {
            setBitStringLiteralTypeName((TBitStringLiteralTypeName) newChild);
            return;
        }

        if(this._hash_ == oldChild)
        {
            setHash((THash) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
