/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanConstant extends PConstant
{
    private PBooleanLiteral _booleanLiteral_;

    public ABooleanConstant()
    {
        // Constructor
    }

    public ABooleanConstant(
        @SuppressWarnings("hiding") PBooleanLiteral _booleanLiteral_)
    {
        // Constructor
        setBooleanLiteral(_booleanLiteral_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanConstant(
            cloneNode(this._booleanLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanConstant(this);
    }

    public PBooleanLiteral getBooleanLiteral()
    {
        return this._booleanLiteral_;
    }

    public void setBooleanLiteral(PBooleanLiteral node)
    {
        if(this._booleanLiteral_ != null)
        {
            this._booleanLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanLiteral_ == child)
        {
            this._booleanLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanLiteral_ == oldChild)
        {
            setBooleanLiteral((PBooleanLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
