/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADateElementaryTypeName extends PElementaryTypeName
{
    private TDateTypeName _dateTypeName_;

    public ADateElementaryTypeName()
    {
        // Constructor
    }

    public ADateElementaryTypeName(
        @SuppressWarnings("hiding") TDateTypeName _dateTypeName_)
    {
        // Constructor
        setDateTypeName(_dateTypeName_);

    }

    @Override
    public Object clone()
    {
        return new ADateElementaryTypeName(
            cloneNode(this._dateTypeName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADateElementaryTypeName(this);
    }

    public TDateTypeName getDateTypeName()
    {
        return this._dateTypeName_;
    }

    public void setDateTypeName(TDateTypeName node)
    {
        if(this._dateTypeName_ != null)
        {
            this._dateTypeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dateTypeName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dateTypeName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dateTypeName_ == child)
        {
            this._dateTypeName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dateTypeName_ == oldChild)
        {
            setDateTypeName((TDateTypeName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
