/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADataTypeLibraryElementDeclaration extends PLibraryElementDeclaration
{
    private PDataTypeDeclaration _dataTypeDeclaration_;

    public ADataTypeLibraryElementDeclaration()
    {
        // Constructor
    }

    public ADataTypeLibraryElementDeclaration(
        @SuppressWarnings("hiding") PDataTypeDeclaration _dataTypeDeclaration_)
    {
        // Constructor
        setDataTypeDeclaration(_dataTypeDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ADataTypeLibraryElementDeclaration(
            cloneNode(this._dataTypeDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADataTypeLibraryElementDeclaration(this);
    }

    public PDataTypeDeclaration getDataTypeDeclaration()
    {
        return this._dataTypeDeclaration_;
    }

    public void setDataTypeDeclaration(PDataTypeDeclaration node)
    {
        if(this._dataTypeDeclaration_ != null)
        {
            this._dataTypeDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dataTypeDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dataTypeDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dataTypeDeclaration_ == child)
        {
            this._dataTypeDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dataTypeDeclaration_ == oldChild)
        {
            setDataTypeDeclaration((PDataTypeDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
