/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADataTypeDeclarationElement extends PDataTypeDeclarationElement
{
    private PTypeDeclaration _typeDeclaration_;
    private TSemicolon _semicolon_;

    public ADataTypeDeclarationElement()
    {
        // Constructor
    }

    public ADataTypeDeclarationElement(
        @SuppressWarnings("hiding") PTypeDeclaration _typeDeclaration_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setTypeDeclaration(_typeDeclaration_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ADataTypeDeclarationElement(
            cloneNode(this._typeDeclaration_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADataTypeDeclarationElement(this);
    }

    public PTypeDeclaration getTypeDeclaration()
    {
        return this._typeDeclaration_;
    }

    public void setTypeDeclaration(PTypeDeclaration node)
    {
        if(this._typeDeclaration_ != null)
        {
            this._typeDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeDeclaration_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeDeclaration_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeDeclaration_ == child)
        {
            this._typeDeclaration_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeDeclaration_ == oldChild)
        {
            setTypeDeclaration((PTypeDeclaration) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
