/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADecimalHours extends PHours
{
    private PFixedPoint _fixedPoint_;
    private THourIdentifier _hourIdentifier_;

    public ADecimalHours()
    {
        // Constructor
    }

    public ADecimalHours(
        @SuppressWarnings("hiding") PFixedPoint _fixedPoint_,
        @SuppressWarnings("hiding") THourIdentifier _hourIdentifier_)
    {
        // Constructor
        setFixedPoint(_fixedPoint_);

        setHourIdentifier(_hourIdentifier_);

    }

    @Override
    public Object clone()
    {
        return new ADecimalHours(
            cloneNode(this._fixedPoint_),
            cloneNode(this._hourIdentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecimalHours(this);
    }

    public PFixedPoint getFixedPoint()
    {
        return this._fixedPoint_;
    }

    public void setFixedPoint(PFixedPoint node)
    {
        if(this._fixedPoint_ != null)
        {
            this._fixedPoint_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fixedPoint_ = node;
    }

    public THourIdentifier getHourIdentifier()
    {
        return this._hourIdentifier_;
    }

    public void setHourIdentifier(THourIdentifier node)
    {
        if(this._hourIdentifier_ != null)
        {
            this._hourIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._hourIdentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fixedPoint_)
            + toString(this._hourIdentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fixedPoint_ == child)
        {
            this._fixedPoint_ = null;
            return;
        }

        if(this._hourIdentifier_ == child)
        {
            this._hourIdentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fixedPoint_ == oldChild)
        {
            setFixedPoint((PFixedPoint) newChild);
            return;
        }

        if(this._hourIdentifier_ == oldChild)
        {
            setHourIdentifier((THourIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
