/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADerivedNonGenericTypeName extends PNonGenericTypeName
{
    private PDerivedTypeName _derivedTypeName_;

    public ADerivedNonGenericTypeName()
    {
        // Constructor
    }

    public ADerivedNonGenericTypeName(
        @SuppressWarnings("hiding") PDerivedTypeName _derivedTypeName_)
    {
        // Constructor
        setDerivedTypeName(_derivedTypeName_);

    }

    @Override
    public Object clone()
    {
        return new ADerivedNonGenericTypeName(
            cloneNode(this._derivedTypeName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADerivedNonGenericTypeName(this);
    }

    public PDerivedTypeName getDerivedTypeName()
    {
        return this._derivedTypeName_;
    }

    public void setDerivedTypeName(PDerivedTypeName node)
    {
        if(this._derivedTypeName_ != null)
        {
            this._derivedTypeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._derivedTypeName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._derivedTypeName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._derivedTypeName_ == child)
        {
            this._derivedTypeName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._derivedTypeName_ == oldChild)
        {
            setDerivedTypeName((PDerivedTypeName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
