/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADerivedFunctionBlockTypeName extends PFunctionBlockTypeName
{
    private PDerivedFunctionBlockName _derivedFunctionBlockName_;

    public ADerivedFunctionBlockTypeName()
    {
        // Constructor
    }

    public ADerivedFunctionBlockTypeName(
        @SuppressWarnings("hiding") PDerivedFunctionBlockName _derivedFunctionBlockName_)
    {
        // Constructor
        setDerivedFunctionBlockName(_derivedFunctionBlockName_);

    }

    @Override
    public Object clone()
    {
        return new ADerivedFunctionBlockTypeName(
            cloneNode(this._derivedFunctionBlockName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADerivedFunctionBlockTypeName(this);
    }

    public PDerivedFunctionBlockName getDerivedFunctionBlockName()
    {
        return this._derivedFunctionBlockName_;
    }

    public void setDerivedFunctionBlockName(PDerivedFunctionBlockName node)
    {
        if(this._derivedFunctionBlockName_ != null)
        {
            this._derivedFunctionBlockName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._derivedFunctionBlockName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._derivedFunctionBlockName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._derivedFunctionBlockName_ == child)
        {
            this._derivedFunctionBlockName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._derivedFunctionBlockName_ == oldChild)
        {
            setDerivedFunctionBlockName((PDerivedFunctionBlockName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
