/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADurationTimeLiteral extends PTimeLiteral
{
    private PDuration _duration_;

    public ADurationTimeLiteral()
    {
        // Constructor
    }

    public ADurationTimeLiteral(
        @SuppressWarnings("hiding") PDuration _duration_)
    {
        // Constructor
        setDuration(_duration_);

    }

    @Override
    public Object clone()
    {
        return new ADurationTimeLiteral(
            cloneNode(this._duration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADurationTimeLiteral(this);
    }

    public PDuration getDuration()
    {
        return this._duration_;
    }

    public void setDuration(PDuration node)
    {
        if(this._duration_ != null)
        {
            this._duration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._duration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._duration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._duration_ == child)
        {
            this._duration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._duration_ == oldChild)
        {
            setDuration((PDuration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
