/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AExternalOtherVarDeclarations extends POtherVarDeclarations
{
    private PExternalVarDeclarations _externalVarDeclarations_;

    public AExternalOtherVarDeclarations()
    {
        // Constructor
    }

    public AExternalOtherVarDeclarations(
        @SuppressWarnings("hiding") PExternalVarDeclarations _externalVarDeclarations_)
    {
        // Constructor
        setExternalVarDeclarations(_externalVarDeclarations_);

    }

    @Override
    public Object clone()
    {
        return new AExternalOtherVarDeclarations(
            cloneNode(this._externalVarDeclarations_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExternalOtherVarDeclarations(this);
    }

    public PExternalVarDeclarations getExternalVarDeclarations()
    {
        return this._externalVarDeclarations_;
    }

    public void setExternalVarDeclarations(PExternalVarDeclarations node)
    {
        if(this._externalVarDeclarations_ != null)
        {
            this._externalVarDeclarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._externalVarDeclarations_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._externalVarDeclarations_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._externalVarDeclarations_ == child)
        {
            this._externalVarDeclarations_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._externalVarDeclarations_ == oldChild)
        {
            setExternalVarDeclarations((PExternalVarDeclarations) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
