/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AHoursInterval extends PInterval
{
    private PHours _hours_;

    public AHoursInterval()
    {
        // Constructor
    }

    public AHoursInterval(
        @SuppressWarnings("hiding") PHours _hours_)
    {
        // Constructor
        setHours(_hours_);

    }

    @Override
    public Object clone()
    {
        return new AHoursInterval(
            cloneNode(this._hours_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHoursInterval(this);
    }

    public PHours getHours()
    {
        return this._hours_;
    }

    public void setHours(PHours node)
    {
        if(this._hours_ != null)
        {
            this._hours_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._hours_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._hours_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._hours_ == child)
        {
            this._hours_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._hours_ == oldChild)
        {
            setHours((PHours) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
