/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AInputIoVarDeclarations extends PIoVarDeclarations
{
    private PInputDeclarations _inputDeclarations_;

    public AInputIoVarDeclarations()
    {
        // Constructor
    }

    public AInputIoVarDeclarations(
        @SuppressWarnings("hiding") PInputDeclarations _inputDeclarations_)
    {
        // Constructor
        setInputDeclarations(_inputDeclarations_);

    }

    @Override
    public Object clone()
    {
        return new AInputIoVarDeclarations(
            cloneNode(this._inputDeclarations_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInputIoVarDeclarations(this);
    }

    public PInputDeclarations getInputDeclarations()
    {
        return this._inputDeclarations_;
    }

    public void setInputDeclarations(PInputDeclarations node)
    {
        if(this._inputDeclarations_ != null)
        {
            this._inputDeclarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inputDeclarations_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inputDeclarations_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inputDeclarations_ == child)
        {
            this._inputDeclarations_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inputDeclarations_ == oldChild)
        {
            setInputDeclarations((PInputDeclarations) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
