/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AIntegerCaseListElement extends PCaseListElement
{
    private TSignedInteger _signedInteger_;

    public AIntegerCaseListElement()
    {
        // Constructor
    }

    public AIntegerCaseListElement(
        @SuppressWarnings("hiding") TSignedInteger _signedInteger_)
    {
        // Constructor
        setSignedInteger(_signedInteger_);

    }

    @Override
    public Object clone()
    {
        return new AIntegerCaseListElement(
            cloneNode(this._signedInteger_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntegerCaseListElement(this);
    }

    public TSignedInteger getSignedInteger()
    {
        return this._signedInteger_;
    }

    public void setSignedInteger(TSignedInteger node)
    {
        if(this._signedInteger_ != null)
        {
            this._signedInteger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._signedInteger_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._signedInteger_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._signedInteger_ == child)
        {
            this._signedInteger_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._signedInteger_ == oldChild)
        {
            setSignedInteger((TSignedInteger) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
