/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AIoFunctionVarDeclaration extends PFunctionVarDeclaration
{
    private PIoVarDeclarations _ioVarDeclarations_;

    public AIoFunctionVarDeclaration()
    {
        // Constructor
    }

    public AIoFunctionVarDeclaration(
        @SuppressWarnings("hiding") PIoVarDeclarations _ioVarDeclarations_)
    {
        // Constructor
        setIoVarDeclarations(_ioVarDeclarations_);

    }

    @Override
    public Object clone()
    {
        return new AIoFunctionVarDeclaration(
            cloneNode(this._ioVarDeclarations_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIoFunctionVarDeclaration(this);
    }

    public PIoVarDeclarations getIoVarDeclarations()
    {
        return this._ioVarDeclarations_;
    }

    public void setIoVarDeclarations(PIoVarDeclarations node)
    {
        if(this._ioVarDeclarations_ != null)
        {
            this._ioVarDeclarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ioVarDeclarations_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ioVarDeclarations_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ioVarDeclarations_ == child)
        {
            this._ioVarDeclarations_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ioVarDeclarations_ == oldChild)
        {
            setIoVarDeclarations((PIoVarDeclarations) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
