/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import java.util.*;
import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ALibrary extends PLibrary
{
    private final LinkedList<PLibraryElementDeclaration> _libraryElementDeclaration_ = new LinkedList<PLibraryElementDeclaration>();

    public ALibrary()
    {
        // Constructor
    }

    public ALibrary(
        @SuppressWarnings("hiding") List<?> _libraryElementDeclaration_)
    {
        // Constructor
        setLibraryElementDeclaration(_libraryElementDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ALibrary(
            cloneList(this._libraryElementDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALibrary(this);
    }

    public LinkedList<PLibraryElementDeclaration> getLibraryElementDeclaration()
    {
        return this._libraryElementDeclaration_;
    }

    public void setLibraryElementDeclaration(List<?> list)
    {
        for(PLibraryElementDeclaration e : this._libraryElementDeclaration_)
        {
            e.parent(null);
        }
        this._libraryElementDeclaration_.clear();

        for(Object obj_e : list)
        {
            PLibraryElementDeclaration e = (PLibraryElementDeclaration) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._libraryElementDeclaration_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._libraryElementDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._libraryElementDeclaration_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PLibraryElementDeclaration> i = this._libraryElementDeclaration_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PLibraryElementDeclaration) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
