/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ALiteralBooleanLiteral extends PBooleanLiteral
{
    private TTrueFalseLiteral _trueFalseLiteral_;

    public ALiteralBooleanLiteral()
    {
        // Constructor
    }

    public ALiteralBooleanLiteral(
        @SuppressWarnings("hiding") TTrueFalseLiteral _trueFalseLiteral_)
    {
        // Constructor
        setTrueFalseLiteral(_trueFalseLiteral_);

    }

    @Override
    public Object clone()
    {
        return new ALiteralBooleanLiteral(
            cloneNode(this._trueFalseLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALiteralBooleanLiteral(this);
    }

    public TTrueFalseLiteral getTrueFalseLiteral()
    {
        return this._trueFalseLiteral_;
    }

    public void setTrueFalseLiteral(TTrueFalseLiteral node)
    {
        if(this._trueFalseLiteral_ != null)
        {
            this._trueFalseLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._trueFalseLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._trueFalseLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._trueFalseLiteral_ == child)
        {
            this._trueFalseLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._trueFalseLiteral_ == oldChild)
        {
            setTrueFalseLiteral((TTrueFalseLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
