/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AMillisecondsInterval extends PInterval
{
    private PMilliseconds _milliseconds_;

    public AMillisecondsInterval()
    {
        // Constructor
    }

    public AMillisecondsInterval(
        @SuppressWarnings("hiding") PMilliseconds _milliseconds_)
    {
        // Constructor
        setMilliseconds(_milliseconds_);

    }

    @Override
    public Object clone()
    {
        return new AMillisecondsInterval(
            cloneNode(this._milliseconds_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMillisecondsInterval(this);
    }

    public PMilliseconds getMilliseconds()
    {
        return this._milliseconds_;
    }

    public void setMilliseconds(PMilliseconds node)
    {
        if(this._milliseconds_ != null)
        {
            this._milliseconds_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._milliseconds_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._milliseconds_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._milliseconds_ == child)
        {
            this._milliseconds_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._milliseconds_ == oldChild)
        {
            setMilliseconds((PMilliseconds) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
