/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AProgramAccessDeclListHead extends PProgramAccessDeclListHead
{
    private PProgramAccessDecl _programAccessDecl_;
    private TSemicolon _semicolon_;

    public AProgramAccessDeclListHead()
    {
        // Constructor
    }

    public AProgramAccessDeclListHead(
        @SuppressWarnings("hiding") PProgramAccessDecl _programAccessDecl_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setProgramAccessDecl(_programAccessDecl_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AProgramAccessDeclListHead(
            cloneNode(this._programAccessDecl_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramAccessDeclListHead(this);
    }

    public PProgramAccessDecl getProgramAccessDecl()
    {
        return this._programAccessDecl_;
    }

    public void setProgramAccessDecl(PProgramAccessDecl node)
    {
        if(this._programAccessDecl_ != null)
        {
            this._programAccessDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programAccessDecl_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programAccessDecl_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programAccessDecl_ == child)
        {
            this._programAccessDecl_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programAccessDecl_ == oldChild)
        {
            setProgramAccessDecl((PProgramAccessDecl) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
