/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ARealTypeNameHashed extends PRealTypeNameHashed
{
    private TRealTypeName _realTypeName_;
    private THash _hash_;

    public ARealTypeNameHashed()
    {
        // Constructor
    }

    public ARealTypeNameHashed(
        @SuppressWarnings("hiding") TRealTypeName _realTypeName_,
        @SuppressWarnings("hiding") THash _hash_)
    {
        // Constructor
        setRealTypeName(_realTypeName_);

        setHash(_hash_);

    }

    @Override
    public Object clone()
    {
        return new ARealTypeNameHashed(
            cloneNode(this._realTypeName_),
            cloneNode(this._hash_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealTypeNameHashed(this);
    }

    public TRealTypeName getRealTypeName()
    {
        return this._realTypeName_;
    }

    public void setRealTypeName(TRealTypeName node)
    {
        if(this._realTypeName_ != null)
        {
            this._realTypeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._realTypeName_ = node;
    }

    public THash getHash()
    {
        return this._hash_;
    }

    public void setHash(THash node)
    {
        if(this._hash_ != null)
        {
            this._hash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._hash_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._realTypeName_)
            + toString(this._hash_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._realTypeName_ == child)
        {
            this._realTypeName_ = null;
            return;
        }

        if(this._hash_ == child)
        {
            this._hash_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._realTypeName_ == oldChild)
        {
            setRealTypeName((TRealTypeName) newChild);
            return;
        }

        if(this._hash_ == oldChild)
        {
            setHash((THash) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
