/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AReturnStatement extends PStatement
{
    private TReturnToken _returnToken_;

    public AReturnStatement()
    {
        // Constructor
    }

    public AReturnStatement(
        @SuppressWarnings("hiding") TReturnToken _returnToken_)
    {
        // Constructor
        setReturnToken(_returnToken_);

    }

    @Override
    public Object clone()
    {
        return new AReturnStatement(
            cloneNode(this._returnToken_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReturnStatement(this);
    }

    public TReturnToken getReturnToken()
    {
        return this._returnToken_;
    }

    public void setReturnToken(TReturnToken node)
    {
        if(this._returnToken_ != null)
        {
            this._returnToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._returnToken_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._returnToken_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._returnToken_ == child)
        {
            this._returnToken_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._returnToken_ == oldChild)
        {
            setReturnToken((TReturnToken) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
