/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASecondsInterval extends PInterval
{
    private PSeconds _seconds_;

    public ASecondsInterval()
    {
        // Constructor
    }

    public ASecondsInterval(
        @SuppressWarnings("hiding") PSeconds _seconds_)
    {
        // Constructor
        setSeconds(_seconds_);

    }

    @Override
    public Object clone()
    {
        return new ASecondsInterval(
            cloneNode(this._seconds_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASecondsInterval(this);
    }

    public PSeconds getSeconds()
    {
        return this._seconds_;
    }

    public void setSeconds(PSeconds node)
    {
        if(this._seconds_ != null)
        {
            this._seconds_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seconds_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._seconds_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._seconds_ == child)
        {
            this._seconds_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._seconds_ == oldChild)
        {
            setSeconds((PSeconds) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
