/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASignedIntegerIntegerTypeName extends PIntegerTypeName
{
    private TSignedIntegerTypeName _signedIntegerTypeName_;

    public ASignedIntegerIntegerTypeName()
    {
        // Constructor
    }

    public ASignedIntegerIntegerTypeName(
        @SuppressWarnings("hiding") TSignedIntegerTypeName _signedIntegerTypeName_)
    {
        // Constructor
        setSignedIntegerTypeName(_signedIntegerTypeName_);

    }

    @Override
    public Object clone()
    {
        return new ASignedIntegerIntegerTypeName(
            cloneNode(this._signedIntegerTypeName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASignedIntegerIntegerTypeName(this);
    }

    public TSignedIntegerTypeName getSignedIntegerTypeName()
    {
        return this._signedIntegerTypeName_;
    }

    public void setSignedIntegerTypeName(TSignedIntegerTypeName node)
    {
        if(this._signedIntegerTypeName_ != null)
        {
            this._signedIntegerTypeName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._signedIntegerTypeName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._signedIntegerTypeName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._signedIntegerTypeName_ == child)
        {
            this._signedIntegerTypeName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._signedIntegerTypeName_ == oldChild)
        {
            setSignedIntegerTypeName((TSignedIntegerTypeName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
