/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleSpecInitialization extends PSimpleSpecInitialization
{
    private TColonEq _colonEq_;
    private PConstant _constant_;

    public ASimpleSpecInitialization()
    {
        // Constructor
    }

    public ASimpleSpecInitialization(
        @SuppressWarnings("hiding") TColonEq _colonEq_,
        @SuppressWarnings("hiding") PConstant _constant_)
    {
        // Constructor
        setColonEq(_colonEq_);

        setConstant(_constant_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleSpecInitialization(
            cloneNode(this._colonEq_),
            cloneNode(this._constant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleSpecInitialization(this);
    }

    public TColonEq getColonEq()
    {
        return this._colonEq_;
    }

    public void setColonEq(TColonEq node)
    {
        if(this._colonEq_ != null)
        {
            this._colonEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colonEq_ = node;
    }

    public PConstant getConstant()
    {
        return this._constant_;
    }

    public void setConstant(PConstant node)
    {
        if(this._constant_ != null)
        {
            this._constant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colonEq_)
            + toString(this._constant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colonEq_ == child)
        {
            this._colonEq_ = null;
            return;
        }

        if(this._constant_ == child)
        {
            this._constant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colonEq_ == oldChild)
        {
            setColonEq((TColonEq) newChild);
            return;
        }

        if(this._constant_ == oldChild)
        {
            setConstant((PConstant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
