/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AStandardFunctionBlockTypeName extends PFunctionBlockTypeName
{
    private TStandardFunctionBlockName _standardFunctionBlockName_;

    public AStandardFunctionBlockTypeName()
    {
        // Constructor
    }

    public AStandardFunctionBlockTypeName(
        @SuppressWarnings("hiding") TStandardFunctionBlockName _standardFunctionBlockName_)
    {
        // Constructor
        setStandardFunctionBlockName(_standardFunctionBlockName_);

    }

    @Override
    public Object clone()
    {
        return new AStandardFunctionBlockTypeName(
            cloneNode(this._standardFunctionBlockName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStandardFunctionBlockTypeName(this);
    }

    public TStandardFunctionBlockName getStandardFunctionBlockName()
    {
        return this._standardFunctionBlockName_;
    }

    public void setStandardFunctionBlockName(TStandardFunctionBlockName node)
    {
        if(this._standardFunctionBlockName_ != null)
        {
            this._standardFunctionBlockName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._standardFunctionBlockName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._standardFunctionBlockName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._standardFunctionBlockName_ == child)
        {
            this._standardFunctionBlockName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._standardFunctionBlockName_ == oldChild)
        {
            setStandardFunctionBlockName((TStandardFunctionBlockName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
