/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AStructTypeTypeDeclaration extends PTypeDeclaration
{
    private PStructureTypeDeclaration _structureTypeDeclaration_;

    public AStructTypeTypeDeclaration()
    {
        // Constructor
    }

    public AStructTypeTypeDeclaration(
        @SuppressWarnings("hiding") PStructureTypeDeclaration _structureTypeDeclaration_)
    {
        // Constructor
        setStructureTypeDeclaration(_structureTypeDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AStructTypeTypeDeclaration(
            cloneNode(this._structureTypeDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStructTypeTypeDeclaration(this);
    }

    public PStructureTypeDeclaration getStructureTypeDeclaration()
    {
        return this._structureTypeDeclaration_;
    }

    public void setStructureTypeDeclaration(PStructureTypeDeclaration node)
    {
        if(this._structureTypeDeclaration_ != null)
        {
            this._structureTypeDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._structureTypeDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._structureTypeDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._structureTypeDeclaration_ == child)
        {
            this._structureTypeDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._structureTypeDeclaration_ == oldChild)
        {
            setStructureTypeDeclaration((PStructureTypeDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
