/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import java.util.*;
import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AStructureElementInitializationList extends PStructureElementInitializationList
{
    private final LinkedList<PStructureElementInitializationListHead> _structureElementInitializationListHead_ = new LinkedList<PStructureElementInitializationListHead>();
    private PStructureElementInitialization _structureElementInitialization_;

    public AStructureElementInitializationList()
    {
        // Constructor
    }

    public AStructureElementInitializationList(
        @SuppressWarnings("hiding") List<?> _structureElementInitializationListHead_,
        @SuppressWarnings("hiding") PStructureElementInitialization _structureElementInitialization_)
    {
        // Constructor
        setStructureElementInitializationListHead(_structureElementInitializationListHead_);

        setStructureElementInitialization(_structureElementInitialization_);

    }

    @Override
    public Object clone()
    {
        return new AStructureElementInitializationList(
            cloneList(this._structureElementInitializationListHead_),
            cloneNode(this._structureElementInitialization_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStructureElementInitializationList(this);
    }

    public LinkedList<PStructureElementInitializationListHead> getStructureElementInitializationListHead()
    {
        return this._structureElementInitializationListHead_;
    }

    public void setStructureElementInitializationListHead(List<?> list)
    {
        for(PStructureElementInitializationListHead e : this._structureElementInitializationListHead_)
        {
            e.parent(null);
        }
        this._structureElementInitializationListHead_.clear();

        for(Object obj_e : list)
        {
            PStructureElementInitializationListHead e = (PStructureElementInitializationListHead) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._structureElementInitializationListHead_.add(e);
        }
    }

    public PStructureElementInitialization getStructureElementInitialization()
    {
        return this._structureElementInitialization_;
    }

    public void setStructureElementInitialization(PStructureElementInitialization node)
    {
        if(this._structureElementInitialization_ != null)
        {
            this._structureElementInitialization_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._structureElementInitialization_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._structureElementInitializationListHead_)
            + toString(this._structureElementInitialization_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._structureElementInitializationListHead_.remove(child))
        {
            return;
        }

        if(this._structureElementInitialization_ == child)
        {
            this._structureElementInitialization_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PStructureElementInitializationListHead> i = this._structureElementInitializationListHead_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStructureElementInitializationListHead) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._structureElementInitialization_ == oldChild)
        {
            setStructureElementInitialization((PStructureElementInitialization) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
