/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AStringTypeDeclarationInitialization extends PStringTypeDeclarationInitialization
{
    private TColonEq _colonEq_;
    private PCharacterString _val_;

    public AStringTypeDeclarationInitialization()
    {
        // Constructor
    }

    public AStringTypeDeclarationInitialization(
        @SuppressWarnings("hiding") TColonEq _colonEq_,
        @SuppressWarnings("hiding") PCharacterString _val_)
    {
        // Constructor
        setColonEq(_colonEq_);

        setVal(_val_);

    }

    @Override
    public Object clone()
    {
        return new AStringTypeDeclarationInitialization(
            cloneNode(this._colonEq_),
            cloneNode(this._val_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringTypeDeclarationInitialization(this);
    }

    public TColonEq getColonEq()
    {
        return this._colonEq_;
    }

    public void setColonEq(TColonEq node)
    {
        if(this._colonEq_ != null)
        {
            this._colonEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colonEq_ = node;
    }

    public PCharacterString getVal()
    {
        return this._val_;
    }

    public void setVal(PCharacterString node)
    {
        if(this._val_ != null)
        {
            this._val_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._val_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colonEq_)
            + toString(this._val_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colonEq_ == child)
        {
            this._colonEq_ = null;
            return;
        }

        if(this._val_ == child)
        {
            this._val_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colonEq_ == oldChild)
        {
            setColonEq((TColonEq) newChild);
            return;
        }

        if(this._val_ == oldChild)
        {
            setVal((PCharacterString) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
