/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AStructSymbolicVariableComplex extends PSymbolicVariableComplex
{
    private PSymbolicVariable _symbolicVariable_;
    private TDot _dot_;
    private PFieldSelector _fieldSelector_;

    public AStructSymbolicVariableComplex()
    {
        // Constructor
    }

    public AStructSymbolicVariableComplex(
        @SuppressWarnings("hiding") PSymbolicVariable _symbolicVariable_,
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") PFieldSelector _fieldSelector_)
    {
        // Constructor
        setSymbolicVariable(_symbolicVariable_);

        setDot(_dot_);

        setFieldSelector(_fieldSelector_);

    }

    @Override
    public Object clone()
    {
        return new AStructSymbolicVariableComplex(
            cloneNode(this._symbolicVariable_),
            cloneNode(this._dot_),
            cloneNode(this._fieldSelector_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStructSymbolicVariableComplex(this);
    }

    public PSymbolicVariable getSymbolicVariable()
    {
        return this._symbolicVariable_;
    }

    public void setSymbolicVariable(PSymbolicVariable node)
    {
        if(this._symbolicVariable_ != null)
        {
            this._symbolicVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._symbolicVariable_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public PFieldSelector getFieldSelector()
    {
        return this._fieldSelector_;
    }

    public void setFieldSelector(PFieldSelector node)
    {
        if(this._fieldSelector_ != null)
        {
            this._fieldSelector_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fieldSelector_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._symbolicVariable_)
            + toString(this._dot_)
            + toString(this._fieldSelector_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._symbolicVariable_ == child)
        {
            this._symbolicVariable_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._fieldSelector_ == child)
        {
            this._fieldSelector_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._symbolicVariable_ == oldChild)
        {
            setSymbolicVariable((PSymbolicVariable) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._fieldSelector_ == oldChild)
        {
            setFieldSelector((PFieldSelector) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
