/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASubscriptListHead extends PSubscriptListHead
{
    private PSubscript _subscript_;
    private TComma _comma_;

    public ASubscriptListHead()
    {
        // Constructor
    }

    public ASubscriptListHead(
        @SuppressWarnings("hiding") PSubscript _subscript_,
        @SuppressWarnings("hiding") TComma _comma_)
    {
        // Constructor
        setSubscript(_subscript_);

        setComma(_comma_);

    }

    @Override
    public Object clone()
    {
        return new ASubscriptListHead(
            cloneNode(this._subscript_),
            cloneNode(this._comma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubscriptListHead(this);
    }

    public PSubscript getSubscript()
    {
        return this._subscript_;
    }

    public void setSubscript(PSubscript node)
    {
        if(this._subscript_ != null)
        {
            this._subscript_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subscript_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subscript_)
            + toString(this._comma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subscript_ == child)
        {
            this._subscript_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subscript_ == oldChild)
        {
            setSubscript((PSubscript) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
