/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASubrangeListHead extends PSubrangeListHead
{
    private PSubrange _subrange_;
    private TComma _comma_;

    public ASubrangeListHead()
    {
        // Constructor
    }

    public ASubrangeListHead(
        @SuppressWarnings("hiding") PSubrange _subrange_,
        @SuppressWarnings("hiding") TComma _comma_)
    {
        // Constructor
        setSubrange(_subrange_);

        setComma(_comma_);

    }

    @Override
    public Object clone()
    {
        return new ASubrangeListHead(
            cloneNode(this._subrange_),
            cloneNode(this._comma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubrangeListHead(this);
    }

    public PSubrange getSubrange()
    {
        return this._subrange_;
    }

    public void setSubrange(PSubrange node)
    {
        if(this._subrange_ != null)
        {
            this._subrange_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subrange_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subrange_)
            + toString(this._comma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subrange_ == child)
        {
            this._subrange_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subrange_ == oldChild)
        {
            setSubrange((PSubrange) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
