/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATempOtherVarDeclarations extends POtherVarDeclarations
{
    private PTempVarDeclarations _tempVarDeclarations_;

    public ATempOtherVarDeclarations()
    {
        // Constructor
    }

    public ATempOtherVarDeclarations(
        @SuppressWarnings("hiding") PTempVarDeclarations _tempVarDeclarations_)
    {
        // Constructor
        setTempVarDeclarations(_tempVarDeclarations_);

    }

    @Override
    public Object clone()
    {
        return new ATempOtherVarDeclarations(
            cloneNode(this._tempVarDeclarations_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATempOtherVarDeclarations(this);
    }

    public PTempVarDeclarations getTempVarDeclarations()
    {
        return this._tempVarDeclarations_;
    }

    public void setTempVarDeclarations(PTempVarDeclarations node)
    {
        if(this._tempVarDeclarations_ != null)
        {
            this._tempVarDeclarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tempVarDeclarations_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tempVarDeclarations_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tempVarDeclarations_ == child)
        {
            this._tempVarDeclarations_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tempVarDeclarations_ == oldChild)
        {
            setTempVarDeclarations((PTempVarDeclarations) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
