/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATempVarDeclarations extends PTempVarDeclarations
{
    private TVarTempToken _varTempToken_;
    private PVarInitDecls _varInitDecls_;
    private TEndVarToken _endVarToken_;

    public ATempVarDeclarations()
    {
        // Constructor
    }

    public ATempVarDeclarations(
        @SuppressWarnings("hiding") TVarTempToken _varTempToken_,
        @SuppressWarnings("hiding") PVarInitDecls _varInitDecls_,
        @SuppressWarnings("hiding") TEndVarToken _endVarToken_)
    {
        // Constructor
        setVarTempToken(_varTempToken_);

        setVarInitDecls(_varInitDecls_);

        setEndVarToken(_endVarToken_);

    }

    @Override
    public Object clone()
    {
        return new ATempVarDeclarations(
            cloneNode(this._varTempToken_),
            cloneNode(this._varInitDecls_),
            cloneNode(this._endVarToken_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATempVarDeclarations(this);
    }

    public TVarTempToken getVarTempToken()
    {
        return this._varTempToken_;
    }

    public void setVarTempToken(TVarTempToken node)
    {
        if(this._varTempToken_ != null)
        {
            this._varTempToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varTempToken_ = node;
    }

    public PVarInitDecls getVarInitDecls()
    {
        return this._varInitDecls_;
    }

    public void setVarInitDecls(PVarInitDecls node)
    {
        if(this._varInitDecls_ != null)
        {
            this._varInitDecls_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varInitDecls_ = node;
    }

    public TEndVarToken getEndVarToken()
    {
        return this._endVarToken_;
    }

    public void setEndVarToken(TEndVarToken node)
    {
        if(this._endVarToken_ != null)
        {
            this._endVarToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endVarToken_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varTempToken_)
            + toString(this._varInitDecls_)
            + toString(this._endVarToken_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varTempToken_ == child)
        {
            this._varTempToken_ = null;
            return;
        }

        if(this._varInitDecls_ == child)
        {
            this._varInitDecls_ = null;
            return;
        }

        if(this._endVarToken_ == child)
        {
            this._endVarToken_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varTempToken_ == oldChild)
        {
            setVarTempToken((TVarTempToken) newChild);
            return;
        }

        if(this._varInitDecls_ == oldChild)
        {
            setVarInitDecls((PVarInitDecls) newChild);
            return;
        }

        if(this._endVarToken_ == oldChild)
        {
            setEndVarToken((TEndVarToken) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
