/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATimeConstant extends PConstant
{
    private PTimeLiteral _timeLiteral_;

    public ATimeConstant()
    {
        // Constructor
    }

    public ATimeConstant(
        @SuppressWarnings("hiding") PTimeLiteral _timeLiteral_)
    {
        // Constructor
        setTimeLiteral(_timeLiteral_);

    }

    @Override
    public Object clone()
    {
        return new ATimeConstant(
            cloneNode(this._timeLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeConstant(this);
    }

    public PTimeLiteral getTimeLiteral()
    {
        return this._timeLiteral_;
    }

    public void setTimeLiteral(PTimeLiteral node)
    {
        if(this._timeLiteral_ != null)
        {
            this._timeLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timeLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._timeLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._timeLiteral_ == child)
        {
            this._timeLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._timeLiteral_ == oldChild)
        {
            setTimeLiteral((PTimeLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
