/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATimeOfDayTimeLiteral extends PTimeLiteral
{
    private PTimeOfDay _timeOfDay_;

    public ATimeOfDayTimeLiteral()
    {
        // Constructor
    }

    public ATimeOfDayTimeLiteral(
        @SuppressWarnings("hiding") PTimeOfDay _timeOfDay_)
    {
        // Constructor
        setTimeOfDay(_timeOfDay_);

    }

    @Override
    public Object clone()
    {
        return new ATimeOfDayTimeLiteral(
            cloneNode(this._timeOfDay_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeOfDayTimeLiteral(this);
    }

    public PTimeOfDay getTimeOfDay()
    {
        return this._timeOfDay_;
    }

    public void setTimeOfDay(PTimeOfDay node)
    {
        if(this._timeOfDay_ != null)
        {
            this._timeOfDay_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timeOfDay_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._timeOfDay_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._timeOfDay_ == child)
        {
            this._timeOfDay_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._timeOfDay_ == oldChild)
        {
            setTimeOfDay((PTimeOfDay) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
