/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AUnaryComparison extends PComparison
{
    private PEquExpression _equExpression_;

    public AUnaryComparison()
    {
        // Constructor
    }

    public AUnaryComparison(
        @SuppressWarnings("hiding") PEquExpression _equExpression_)
    {
        // Constructor
        setEquExpression(_equExpression_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryComparison(
            cloneNode(this._equExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryComparison(this);
    }

    public PEquExpression getEquExpression()
    {
        return this._equExpression_;
    }

    public void setEquExpression(PEquExpression node)
    {
        if(this._equExpression_ != null)
        {
            this._equExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equExpression_ == child)
        {
            this._equExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equExpression_ == oldChild)
        {
            setEquExpression((PEquExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
