/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AUnaryXorExpression extends PXorExpression
{
    private PAndExpression _andExpression_;

    public AUnaryXorExpression()
    {
        // Constructor
    }

    public AUnaryXorExpression(
        @SuppressWarnings("hiding") PAndExpression _andExpression_)
    {
        // Constructor
        setAndExpression(_andExpression_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryXorExpression(
            cloneNode(this._andExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryXorExpression(this);
    }

    public PAndExpression getAndExpression()
    {
        return this._andExpression_;
    }

    public void setAndExpression(PAndExpression node)
    {
        if(this._andExpression_ != null)
        {
            this._andExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andExpression_ == child)
        {
            this._andExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._andExpression_ == oldChild)
        {
            setAndExpression((PAndExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
