/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AWhileIterationStatement extends PIterationStatement
{
    private PWhileStatement _whileStatement_;

    public AWhileIterationStatement()
    {
        // Constructor
    }

    public AWhileIterationStatement(
        @SuppressWarnings("hiding") PWhileStatement _whileStatement_)
    {
        // Constructor
        setWhileStatement(_whileStatement_);

    }

    @Override
    public Object clone()
    {
        return new AWhileIterationStatement(
            cloneNode(this._whileStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileIterationStatement(this);
    }

    public PWhileStatement getWhileStatement()
    {
        return this._whileStatement_;
    }

    public void setWhileStatement(PWhileStatement node)
    {
        if(this._whileStatement_ != null)
        {
            this._whileStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileStatement_ == child)
        {
            this._whileStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileStatement_ == oldChild)
        {
            setWhileStatement((PWhileStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
