/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TArrayToken extends Token
{
    public TArrayToken()
    {
        super.setText("ARRAY");
    }

    public TArrayToken(int line, int pos)
    {
        super.setText("ARRAY");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArrayToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArrayToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArrayToken text.");
    }
}
