/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TAtToken extends Token
{
    public TAtToken()
    {
        super.setText("AT");
    }

    public TAtToken(int line, int pos)
    {
        super.setText("AT");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtToken text.");
    }
}
