/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TConstantToken extends Token
{
    public TConstantToken()
    {
        super.setText("CONSTANT");
    }

    public TConstantToken(int line, int pos)
    {
        super.setText("CONSTANT");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TConstantToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConstantToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TConstantToken text.");
    }
}
