/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TDayIdentifier extends Token
{
    public TDayIdentifier()
    {
        super.setText("d");
    }

    public TDayIdentifier(int line, int pos)
    {
        super.setText("d");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDayIdentifier(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDayIdentifier(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDayIdentifier text.");
    }
}
