/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TElseToken extends Token
{
    public TElseToken()
    {
        super.setText("ELSE");
    }

    public TElseToken(int line, int pos)
    {
        super.setText("ELSE");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TElseToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTElseToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TElseToken text.");
    }
}
