/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TEndCaseToken extends Token
{
    public TEndCaseToken()
    {
        super.setText("END_CASE");
    }

    public TEndCaseToken(int line, int pos)
    {
        super.setText("END_CASE");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndCaseToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndCaseToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndCaseToken text.");
    }
}
