/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TEndForToken extends Token
{
    public TEndForToken()
    {
        super.setText("END_FOR");
    }

    public TEndForToken(int line, int pos)
    {
        super.setText("END_FOR");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndForToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndForToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndForToken text.");
    }
}
