/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TEndTypeToken extends Token
{
    public TEndTypeToken()
    {
        super.setText("END_TYPE");
    }

    public TEndTypeToken(int line, int pos)
    {
        super.setText("END_TYPE");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndTypeToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndTypeToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndTypeToken text.");
    }
}
