/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TEndVarToken extends Token
{
    public TEndVarToken()
    {
        super.setText("END_VAR");
    }

    public TEndVarToken(int line, int pos)
    {
        super.setText("END_VAR");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndVarToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndVarToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndVarToken text.");
    }
}
