/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TForToken extends Token
{
    public TForToken()
    {
        super.setText("FOR");
    }

    public TForToken(int line, int pos)
    {
        super.setText("FOR");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TForToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTForToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TForToken text.");
    }
}
