/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class THourIdentifier extends Token
{
    public THourIdentifier()
    {
        super.setText("h");
    }

    public THourIdentifier(int line, int pos)
    {
        super.setText("h");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THourIdentifier(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHourIdentifier(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THourIdentifier text.");
    }
}
