/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TMillisecondIdentifier extends Token
{
    public TMillisecondIdentifier()
    {
        super.setText("ms");
    }

    public TMillisecondIdentifier(int line, int pos)
    {
        super.setText("ms");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMillisecondIdentifier(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMillisecondIdentifier(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMillisecondIdentifier text.");
    }
}
