/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TNonRetainToken extends Token
{
    public TNonRetainToken()
    {
        super.setText("NON_RETAIN");
    }

    public TNonRetainToken(int line, int pos)
    {
        super.setText("NON_RETAIN");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNonRetainToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNonRetainToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNonRetainToken text.");
    }
}
