/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TRepeatToken extends Token
{
    public TRepeatToken()
    {
        super.setText("REPEAT");
    }

    public TRepeatToken(int line, int pos)
    {
        super.setText("REPEAT");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRepeatToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRepeatToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRepeatToken text.");
    }
}
