/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TRetainToken extends Token
{
    public TRetainToken()
    {
        super.setText("RETAIN");
    }

    public TRetainToken(int line, int pos)
    {
        super.setText("RETAIN");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRetainToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRetainToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRetainToken text.");
    }
}
