/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TSecondIdentifier extends Token
{
    public TSecondIdentifier()
    {
        super.setText("s");
    }

    public TSecondIdentifier(int line, int pos)
    {
        super.setText("s");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSecondIdentifier(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSecondIdentifier(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSecondIdentifier text.");
    }
}
