/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TStandardFunctionBlockName extends Token
{
    public TStandardFunctionBlockName(String text)
    {
        setText(text);
    }

    public TStandardFunctionBlockName(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStandardFunctionBlockName(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStandardFunctionBlockName(this);
    }
}
