/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TStructToken extends Token
{
    public TStructToken()
    {
        super.setText("STRUCT");
    }

    public TStructToken(int line, int pos)
    {
        super.setText("STRUCT");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStructToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStructToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStructToken text.");
    }
}
