/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TTimeTypeName extends Token
{
    public TTimeTypeName()
    {
        super.setText("TIME");
    }

    public TTimeTypeName(int line, int pos)
    {
        super.setText("TIME");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTimeTypeName(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTimeTypeName(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTimeTypeName text.");
    }
}
