/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TTypeToken extends Token
{
    public TTypeToken()
    {
        super.setText("TYPE");
    }

    public TTypeToken(int line, int pos)
    {
        super.setText("TYPE");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTypeToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTypeToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTypeToken text.");
    }
}
