/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TUnsignedIntegerLiteral extends Token
{
    public TUnsignedIntegerLiteral(String text)
    {
        setText(text);
    }

    public TUnsignedIntegerLiteral(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUnsignedIntegerLiteral(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnsignedIntegerLiteral(this);
    }
}
