/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TUntilToken extends Token
{
    public TUntilToken()
    {
        super.setText("UNTIL");
    }

    public TUntilToken(int line, int pos)
    {
        super.setText("UNTIL");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUntilToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUntilToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUntilToken text.");
    }
}
