/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TVarExternalToken extends Token
{
    public TVarExternalToken()
    {
        super.setText("VAR_EXTERNAL");
    }

    public TVarExternalToken(int line, int pos)
    {
        super.setText("VAR_EXTERNAL");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVarExternalToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVarExternalToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVarExternalToken text.");
    }
}
