/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TVarOutputToken extends Token
{
    public TVarOutputToken()
    {
        super.setText("VAR_OUTPUT");
    }

    public TVarOutputToken(int line, int pos)
    {
        super.setText("VAR_OUTPUT");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVarOutputToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVarOutputToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVarOutputToken text.");
    }
}
