/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TVarTempToken extends Token
{
    public TVarTempToken()
    {
        super.setText("VAR_TEMP");
    }

    public TVarTempToken(int line, int pos)
    {
        super.setText("VAR_TEMP");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVarTempToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVarTempToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVarTempToken text.");
    }
}
