/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TVarAccessToken extends Token
{
    public TVarAccessToken()
    {
        super.setText("VAR_ACCESS");
    }

    public TVarAccessToken(int line, int pos)
    {
        super.setText("VAR_ACCESS");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVarAccessToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVarAccessToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVarAccessToken text.");
    }
}
