/* This file was generated by SableCC (http://www.sablecc.org/). */

package javast.sablecc.node;

import javast.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TWstringTypeName extends Token
{
    public TWstringTypeName()
    {
        super.setText("WSTRING");
    }

    public TWstringTypeName(int line, int pos)
    {
        super.setText("WSTRING");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TWstringTypeName(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWstringTypeName(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TWstringTypeName text.");
    }
}
